# Generated by Django 3.1.5 on 2021-01-28 09:18

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='category',
        ),
        migrations.AlterField(
            model_name='driver',
            name='bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='app.place')),
                ('location', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='app.driver')),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='pickup_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.place'),
        ),
    ]
