# Generated by Django 3.1.5 on 2021-01-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210128_1552'),
        ('userapp', '0003_auto_20210128_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
