# Generated by Django 3.1.5 on 2021-01-29 04:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_plate',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='seat_number',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
