# Generated by Django 3.1.5 on 2021-01-29 04:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210129_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='arrival_destination',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='pickup_location',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
