# Generated by Django 3.1.5 on 2021-01-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210129_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='car_brand',
        ),
    ]
