# Generated by Django 3.1.5 on 2021-01-29 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210129_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.driver'),
        ),
    ]
