# Generated by Django 3.1.5 on 2021-01-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210129_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='pickup_location',
            new_name='pickup_name',
        ),
    ]
